- name: Copy elastic search repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: restart ELK
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Copy filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

                                        
- name: Restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted

