- name: copy the rsyslog configuration
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/roboshop.conf

- name: Restart the rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted



