- name: Update the prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart the prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

