- name: Install golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Remove app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: add app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory

#- name: Download and Extract {{ COMPONENT }} content
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/refs/heads/main.zip
#    dest: /tmp
#    remote_src: yes

#
#- name: copy {{ COMPONENT }}
#  ansible.builtin.copy:
#    src: /tmp/{{ COMPONENT }}-main/{{SUFFIX}}
#    dest: "{{ APP_LOCATION }}/"
#    remote_src: yes

- name: App setup {{ COMPONENT }} content
  ansible.builtin.include_role:
    name: common
    tasks_from: download


- name: Install golang dependencies
  ansible.builtin.shell: go mod init {{ COMPONENT }} && go get && go build
  args:
    chdir: "{{ APP_LOCATION }}"

- name: Include common role from systemd
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd
