- name: Install golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App setup {{ COMPONENT }} content
  ansible.builtin.include_role:
    name: common
    tasks_from: download
    
#- name: Install golang dependencies
#  ansible.builtin.shell: go mod init {{ COMPONENT }} && go get && go build
#  args:
#    chdir: "{{ APP_LOCATION }}"

- name: Include common role from systemd
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd
