- name: Copy systemd configuration
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: start {{ COMPONENT }} service
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    enabled: yes
    state: restarted
    daemon_reload: yes